### ISSUE TITLE
Need better folder and package structure for beacon chain and shard chain

### ISSUE THREAD

**Issue by wqking** [phoreproject/synapse#19]
Currently the folder 'blockchain' and the package 'blockchain' are used by beacon chain, and 'database' is used by beacon chain too.  
If the shard chain is under the same name, it will be confusing.  
So we may consider to use 'beacon' for beacon chain related stuff, and 'shard' for shard chain?

**Comment by meyer9** [comment]
This seems like a good idea. We should have `beacon`, `p2p`, `validator`, `shard` for each module.

**Comment by wqking** [comment]
Fixed this issue in PR #22
